### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by amnedgeToulouse** [RaiaN/ue4_runtimeimageloader#12]
Hello I create a system of replicated graffity with the help of your plugin to create a cache system for each graff, but I found a memoryleak in your plugin, because when I load many png then close the editor the vram is not flush so you can simply code this:

![image](https://user-images.githubusercontent.com/59095122/167391122-cf858908-6522-4a39-aef3-2d14c0690489.png)

To reproduce the memory leak, so you start the game then you stop you restart.. And you can see the vram increasing without flushing. Let me know if you need more information or if I simply need to do something to handle this myself thank in advance !

**Comment by RaiaN** [comment]
Hi @amnedgeToulouse! Thanks for feedback and sorry for the memory leak :( I've previously tested the plugin with GC collection enabled... 

Let me reproduce this error and fix it!

**Comment by RaiaN** [comment]
Hey @amnedgeToulouse. Not sure how you got the memory leak but I don't see the same when looking at Task Manager vram. 
Can you please share your setup in more details? 

P.S. Unreal has GC that is activated every N seconds so that is why you maybe experiencing what you posted above.

**Comment by amnedgeToulouse** [comment]
Hey @RaiaN Hum I got basic unreal parameter I don't modify GC parameter maybe I have something to do there ? I create a video that show you some information, and I let the editor open for many times and the memory doesn't go down, maybe try with a big image that you load like me, can you show me your code to test the bug ?

The video:
https://www.youtube.com/watch?v=G4yXumI40nk

**Comment by RaiaN** [comment]
@amnedgeToulouse Thanks! Let me see what is going on...

**Comment by RaiaN** [comment]
@amnedgeToulouse Thanks for report! I've fixed the memory leak. Feel free to grab new release:
>https://github.com/RaiaN/ue4_runtimeimageloader/releases/tag/1.1.4

**Comment by RaiaN** [comment]
4.27 or 5.0?

**Comment by RaiaN** [comment]
@amnedgeToulouse Just updated the latest release.

**Comment by amnedgeToulouse** [comment]
Hey @RaiaN I download the update from epic game store but I still got the same issue I reproduce it like it in the video. Maybe I have to wait a specific amount of time before the memory flush ??

**Comment by FlamingFuryVN** [comment]
![image](https://user-images.githubusercontent.com/60380576/167836974-396042e0-1254-4413-a179-db268eed2734.png)
Exactly is 61.099998s, you can decrease it if you want. But it causes a drop FPS every time it is active, so don't set it 1 or 2 seconds.  Or you can call it from BP by "Collect Garbage" when you clear the widget (Make sure that widget doesn't have any reference from others, it means not save by any Variable in any Blueprint)

**Comment by RaiaN** [comment]
@amnedgeToulouse Update was released on Epic Games Marketplace late yesterday! Now you should not see any memory leaks

**Comment by RaiaN** [comment]
@FlamingFuryVN 
@amnedgeToulouse was talking about GPU vRAM memory leak. Previously I didn't cleanup all texture references properly so even if GC did its job texture would still be in GPU memory.

**Comment by FlamingFuryVN** [comment]
> @FlamingFuryVN @amnedgeToulouse was talking about GPU vRAM memory leak. Previously I didn't cleanup all texture references properly so even if GC did its job the texture would still be in GPU memory.

Yes, I know. I already test them (The newest version) every time I use GC without saving history on my project. The VRAM goes down as well. But if not using GC, the VRAM is still there. Keep increasing when loading new. Auto GC is only active after 60s

**Comment by RaiaN** [comment]
Ah, gotcha. Yeah, that is consequence of Unreal GC system. Texture object is not destroyed until GC does so (or until there is an explicit request to destroy such texture object)
