### ISSUE TITLE
Release for Unreal Engine 5 ?

### ISSUE THREAD

**Issue by AlePre2** [RaiaN/ue4_runtimeimageloader#2]

**Comment by RaiaN** [comment]
This is planned. Should be done in 1- 2 weeks.

**Comment by ssuukk** [comment]
Either this or just explain how to enable building it from own project.

**Comment by RaiaN** [comment]
I briefly looked into this and it seems that the plugin can be compiled for UE5 easily. Just download latest release of the plugin and put it to YOUR_UE5_PROJECT_DIR/Plugins. Let me know if you have any issues

**Comment by RaiaN** [comment]
I'm still planning to roll out UE5 ready plugin on Marketplace

**Comment by RaiaN** [comment]
Okay, 5.0 is ready @ssuukk ! You can either grab it from Marketplace or right here on Github.
