### ISSUE TITLE
16bit PNG file is not supported

### ISSUE THREAD

**Issue by FlamingFuryVN** [RaiaN/ue4_runtimeimageloader#5]
![image](https://user-images.githubusercontent.com/60380576/161421911-67009288-35bb-42f2-a769-a5aab4fa3fe6.png)
Output from "Out Error" and PrintString in node "Load Image Async"

**Comment by RaiaN** [comment]
Thanks @FlamingFuryVN I recall testing 16-bit PNG images but it could be I skipped some corner cases

**Comment by RaiaN** [comment]
@FlamingFuryVN The issue was fixed. Marketplace update is pending

**Comment by RaiaN** [comment]
Please use a new "For UI" option so your texture is ready for UMG
