### ISSUE TITLE
Add a new option "target size" (feature request from marketplace)

### ISSUE THREAD

**Issue by RaiaN** [RaiaN/ue4_runtimeimageloader#6]

**Comment by RaiaN** [comment]
Implemented. Grab latest release!

**Comment by FlamingFuryVN** [comment]
I just saw this feature on update but can you make it to percent size? Because how do you know the size of the image before loading, it causes the aspect ratio not quite right if just write down a random size

**Comment by RaiaN** [comment]
@FlamingFuryVN Oh, percent size is definitely better. I like it. I will change the functionality, no problem

**Comment by RaiaN** [comment]
@FlamingFuryVN I've implemented 'percent size' feature. Please grab the latest release

**Comment by FlamingFuryVN** [comment]
> @FlamingFuryVN I've implemented 'percent size' feature. Please grab the latest release

Is it updated yet? Because I epic still not noticed an update, or is it still on Pending by epic? I tried to reinstall the plugin but seems not to work tho.

**Comment by FlamingFuryVN** [comment]
> @FlamingFuryVN I've implemented 'percent size' feature. Please grab the latest release

Is it actually imported faster if l lower percent size? I just test on my project (Work as a gallery image) but it no difference between them.
![image](https://user-images.githubusercontent.com/60380576/167401105-71e95219-ca50-4517-8395-52b5c878019a.png)
I had progress bar loading depending on how many child already had in the widget, so I spot them not faster, I guess.

**Comment by FlamingFuryVN** [comment]
@RaiaN Oh, I expect that would be faster if lower size, but it would be so nice if it does. Because benefit from re-size image when import just for faster import. I could give you my project with Gallery Widget if you want. It could help you in testing with tons of images.

**Comment by RaiaN** [comment]
Telegram: yolo_star
